### ISSUE TITLE
Error: No viable overloaded '='

### ISSUE THREAD

**Issue by felixdollack** [rystylee/ofxLibTorch#3]
When I try to compile I am stuck with the error `No viable overloaded '='`.
It appears in BaseModel.cpp in line 18:

> mModule = torch::jit::load(modelPath, *mDevice.get());

I am compiling on macOS 10.14.6 with Xcode 10.3.

I see that mModule is a std::unique_ptrm, but from the documentation of torch::jit::load I don't really see if the returned object is also a pointer or something else.
Can you help fix this error?

**Comment by felixdollack** [comment]
By the way, the project compiles when I remove line 18 from BaseModel.cpp.

**Comment by rystylee** [comment]
I fixed this problem with the latest commit. Please have a look!

**Comment by felixdollack** [comment]
Thank you 👍
